/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Informacion;

import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.awt.Image;
import java.awt.event.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;

public class ActualizarInformacionPDC extends javax.swing.JPanel {

    /**
     * Creates new form ActualizarInformacionPDC
     */
    public ActualizarInformacionPDC() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelActualizarPDC = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        BotonActualizarInformacion = new javax.swing.JButton();
        NuevoCorreoPDC = new javax.swing.JTextField();
        NuevoSexoPDC = new javax.swing.JTextField();
        ContraseñaPDC = new javax.swing.JTextField();
        NuevoNombrePDC = new javax.swing.JTextField();
        NuevoApellidoPDC = new javax.swing.JTextField();
        NuevaIdentificacionPDC = new javax.swing.JTextField();
        NuevaEdadPDC = new javax.swing.JTextField();
        NuevaNacionalidadPDC = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        NuevaContraseñaPDC = new javax.swing.JTextField();
        SubirNuevaFotoPerfil = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        VistaPreviaFotoPerfilPDC = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelActualizarPDC.setBackground(new java.awt.Color(255, 255, 255));
        PanelActualizarPDC.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(29, 35, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Actualizar información");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, -1, -1));

        PanelActualizarPDC.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 60));

        jPanel3.setBackground(new java.awt.Color(180, 180, 195));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Nueva contraseña:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Apellido:");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Identificación:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Edad:");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Sexo:");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, -1));

        jSeparator9.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 390, 10));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 390, 10));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 390, 10));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 390, 10));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 390, 10));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Nombre:");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 390, 10));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Correo electronico:");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 390, 10));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Nacionalidad:");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Contraseña*:");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        jSeparator10.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 390, 10));

        BotonActualizarInformacion.setText("Actualizar infotmación");
        BotonActualizarInformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonActualizarInformacionActionPerformed(evt);
            }
        });
        jPanel3.add(BotonActualizarInformacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 170, 30));

        NuevoCorreoPDC.setBackground(new java.awt.Color(180, 180, 195));
        NuevoCorreoPDC.setBorder(null);
        NuevoCorreoPDC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoCorreoPDCActionPerformed(evt);
            }
        });
        jPanel3.add(NuevoCorreoPDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 250, 30));

        NuevoSexoPDC.setBackground(new java.awt.Color(180, 180, 195));
        NuevoSexoPDC.setBorder(null);
        NuevoSexoPDC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoSexoPDCActionPerformed(evt);
            }
        });
        jPanel3.add(NuevoSexoPDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 340, 30));

        ContraseñaPDC.setBackground(new java.awt.Color(180, 180, 195));
        ContraseñaPDC.setBorder(null);
        jPanel3.add(ContraseñaPDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 290, 30));

        NuevoNombrePDC.setBackground(new java.awt.Color(180, 180, 195));
        NuevoNombrePDC.setBorder(null);
        jPanel3.add(NuevoNombrePDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 320, 30));

        NuevoApellidoPDC.setBackground(new java.awt.Color(180, 180, 195));
        NuevoApellidoPDC.setBorder(null);
        NuevoApellidoPDC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoApellidoPDCActionPerformed(evt);
            }
        });
        jPanel3.add(NuevoApellidoPDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 320, 30));

        NuevaIdentificacionPDC.setBackground(new java.awt.Color(180, 180, 195));
        NuevaIdentificacionPDC.setBorder(null);
        jPanel3.add(NuevaIdentificacionPDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 280, 30));

        NuevaEdadPDC.setBackground(new java.awt.Color(180, 180, 195));
        NuevaEdadPDC.setBorder(null);
        NuevaEdadPDC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevaEdadPDCActionPerformed(evt);
            }
        });
        jPanel3.add(NuevaEdadPDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 340, 30));

        NuevaNacionalidadPDC.setBackground(new java.awt.Color(180, 180, 195));
        NuevaNacionalidadPDC.setBorder(null);
        NuevaNacionalidadPDC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevaNacionalidadPDCActionPerformed(evt);
            }
        });
        jPanel3.add(NuevaNacionalidadPDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 290, 30));

        jSeparator11.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 390, 10));

        NuevaContraseñaPDC.setBackground(new java.awt.Color(180, 180, 195));
        NuevaContraseñaPDC.setBorder(null);
        NuevaContraseñaPDC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevaContraseñaPDCActionPerformed(evt);
            }
        });
        jPanel3.add(NuevaContraseñaPDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 250, 30));

        PanelActualizarPDC.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 520, 450));

        SubirNuevaFotoPerfil.setText("Subir foto de perfil");
        SubirNuevaFotoPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubirNuevaFotoPerfilActionPerformed(evt);
            }
        });
        PanelActualizarPDC.add(SubirNuevaFotoPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 500, 140, 30));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Vista previa foto de perfil");
        PanelActualizarPDC.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 170, -1, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(VistaPreviaFotoPerfilPDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 250));

        PanelActualizarPDC.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 210, 220, 270));

        jPanel5.setBackground(new java.awt.Color(139, 139, 157));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        PanelActualizarPDC.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1050, 80));

        add(PanelActualizarPDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 580));
    }// </editor-fold>//GEN-END:initComponents

    private void BotonActualizarInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonActualizarInformacionActionPerformed
        String contraseña = ContraseñaPDC.getText();
        String correoElectronico = NuevoCorreoPDC.getText();
        String nombre = NuevoNombrePDC.getText();
        String apellido = NuevoApellidoPDC.getText();
        String identificacion = NuevaIdentificacionPDC.getText();
        String nacionalidad = NuevaNacionalidadPDC.getText();
        String nuevaContraseña = NuevaContraseñaPDC.getText();
        String sexo = NuevoSexoPDC.getText();

    }//GEN-LAST:event_BotonActualizarInformacionActionPerformed

    private void NuevoCorreoPDCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoCorreoPDCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NuevoCorreoPDCActionPerformed

    private void NuevoApellidoPDCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoApellidoPDCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NuevoApellidoPDCActionPerformed

    private void NuevoSexoPDCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoSexoPDCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NuevoSexoPDCActionPerformed

    private void NuevaNacionalidadPDCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevaNacionalidadPDCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NuevaNacionalidadPDCActionPerformed

    private void NuevaEdadPDCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevaEdadPDCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NuevaEdadPDCActionPerformed

    private void NuevaContraseñaPDCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevaContraseñaPDCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NuevaContraseñaPDCActionPerformed

    private void SubirNuevaFotoPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubirNuevaFotoPerfilActionPerformed
        SubirNuevaFotoPerfil.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JFileChooser fileChooser = new JFileChooser();
                FileNameExtensionFilter filter = new FileNameExtensionFilter(
                        "Imágenes (JPG, PNG, GIF)", "jpg", "jpeg", "png", "gif");
                fileChooser.setFileFilter(filter);

                int resultado = fileChooser.showOpenDialog(null); // O "this" si estás dentro del JFrame

                if (resultado == JFileChooser.APPROVE_OPTION) {
                    File selectedImageFile = fileChooser.getSelectedFile();

                    try {
                        BufferedImage originalImage = ImageIO.read(selectedImageFile);

                        ImageIcon icon = new ImageIcon(originalImage);
                        Image img = icon.getImage();
                        Image imgEscalada = img.getScaledInstance(
                                VistaPreviaFotoPerfilPDC.getWidth(),
                                VistaPreviaFotoPerfilPDC.getHeight(),
                                Image.SCALE_SMOOTH);

                        VistaPreviaFotoPerfilPDC.setIcon(new ImageIcon(imgEscalada));

                    } catch (IOException ex) {
                        JOptionPane.showMessageDialog(null,
                                "Error al cargar la imagen: " + ex.getMessage(),
                                "Error",
                                JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        });
    }//GEN-LAST:event_SubirNuevaFotoPerfilActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonActualizarInformacion;
    private javax.swing.JTextField ContraseñaPDC;
    private javax.swing.JTextField NuevaContraseñaPDC;
    private javax.swing.JTextField NuevaEdadPDC;
    private javax.swing.JTextField NuevaIdentificacionPDC;
    private javax.swing.JTextField NuevaNacionalidadPDC;
    private javax.swing.JTextField NuevoApellidoPDC;
    private javax.swing.JTextField NuevoCorreoPDC;
    private javax.swing.JTextField NuevoNombrePDC;
    private javax.swing.JTextField NuevoSexoPDC;
    private javax.swing.JPanel PanelActualizarPDC;
    private javax.swing.JButton SubirNuevaFotoPerfil;
    private javax.swing.JLabel VistaPreviaFotoPerfilPDC;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    // End of variables declaration//GEN-END:variables
}
