/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Informacion;

import java.awt.Color;

/**
 *
 * @author ASUS
 */
public class HistorialVisitasPreso extends javax.swing.JPanel {

    /**
     * Creates new form HistorialVisitasPreso
     */
    public HistorialVisitasPreso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PanelHistorialVisitasPDC = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        PanelHistorialVisitantesPDC = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        TabbedHistorialVisitas = new javax.swing.JTabbedPane();
        PanelHistorialVisitas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaHistorialVisitasPDC = new javax.swing.JTable();
        BarraDeBusquedaCodigoVisitas = new javax.swing.JTextField();
        BuscarVisitaPorCodigoBoton = new javax.swing.JButton();
        PanelHistorialVisitantes = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaHistorialVisitantesPDC = new javax.swing.JTable();
        BarraDeBusquedaPorIdentificacionVisitantes = new javax.swing.JTextField();
        BuscarVisitantePorIdentificacionPDC = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(29, 35, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelHistorialVisitasPDC.setBackground(new java.awt.Color(29, 35, 51));
        PanelHistorialVisitasPDC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelHistorialVisitasPDCMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelHistorialVisitasPDCMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelHistorialVisitasPDCMouseExited(evt);
            }
        });
        PanelHistorialVisitasPDC.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("HISTORIAL DE VISITAS");
        PanelHistorialVisitasPDC.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, 30));

        jPanel1.add(PanelHistorialVisitasPDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 70));

        PanelHistorialVisitantesPDC.setBackground(new java.awt.Color(29, 35, 51));
        PanelHistorialVisitantesPDC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelHistorialVisitantesPDCMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelHistorialVisitantesPDCMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelHistorialVisitantesPDCMouseExited(evt);
            }
        });
        PanelHistorialVisitantesPDC.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("HISTORIAL DE VISITANTES");
        PanelHistorialVisitantesPDC.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, 30));

        jButton1.setText("Regresar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        PanelHistorialVisitantesPDC.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, -1, -1));

        jPanel1.add(PanelHistorialVisitantesPDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 540, 70));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 70));

        PanelHistorialVisitas.setBackground(new java.awt.Color(255, 255, 255));
        PanelHistorialVisitas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaHistorialVisitasPDC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Codigo", "Visitante", "Fecha", "Hora", "Duracion", "tipo", "Lugar"
            }
        ));
        jScrollPane1.setViewportView(TablaHistorialVisitasPDC);

        PanelHistorialVisitas.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 1010, 390));

        BarraDeBusquedaCodigoVisitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarraDeBusquedaCodigoVisitasActionPerformed(evt);
            }
        });
        PanelHistorialVisitas.add(BarraDeBusquedaCodigoVisitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 580, 30));

        BuscarVisitaPorCodigoBoton.setText("Buscar");
        PanelHistorialVisitas.add(BuscarVisitaPorCodigoBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 30, 80, 30));

        TabbedHistorialVisitas.addTab("Historial de visitas", PanelHistorialVisitas);

        PanelHistorialVisitantes.setBackground(new java.awt.Color(255, 255, 255));
        PanelHistorialVisitantes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaHistorialVisitantesPDC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Codigo visita", "Nombre", "Apellido", "Identificacion", "Sexo", "Nacionalidad", "Relación"
            }
        ));
        jScrollPane2.setViewportView(TablaHistorialVisitantesPDC);

        PanelHistorialVisitantes.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 990, 410));
        PanelHistorialVisitantes.add(BarraDeBusquedaPorIdentificacionVisitantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 600, 30));

        BuscarVisitantePorIdentificacionPDC.setText("Buscar");
        PanelHistorialVisitantes.add(BuscarVisitantePorIdentificacionPDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 30, 90, 30));

        TabbedHistorialVisitas.addTab("Historial de visitante", PanelHistorialVisitantes);

        add(TabbedHistorialVisitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1050, 560));
    }// </editor-fold>//GEN-END:initComponents

    private void PanelHistorialVisitasPDCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelHistorialVisitasPDCMouseClicked
        TabbedHistorialVisitas.setSelectedIndex(0);
    }//GEN-LAST:event_PanelHistorialVisitasPDCMouseClicked

    private void PanelHistorialVisitantesPDCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelHistorialVisitantesPDCMouseClicked
        TabbedHistorialVisitas.setSelectedIndex(1);
    }//GEN-LAST:event_PanelHistorialVisitantesPDCMouseClicked

    private void PanelHistorialVisitasPDCMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelHistorialVisitasPDCMouseEntered
        PanelHistorialVisitasPDC.setBackground(new Color(43, 54, 84));
    }//GEN-LAST:event_PanelHistorialVisitasPDCMouseEntered

    private void PanelHistorialVisitasPDCMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelHistorialVisitasPDCMouseExited
        PanelHistorialVisitasPDC.setBackground(new Color(29, 35, 51));
    }//GEN-LAST:event_PanelHistorialVisitasPDCMouseExited

    private void PanelHistorialVisitantesPDCMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelHistorialVisitantesPDCMouseEntered
        PanelHistorialVisitantesPDC.setBackground(new Color(43, 54, 84));
    }//GEN-LAST:event_PanelHistorialVisitantesPDCMouseEntered

    private void PanelHistorialVisitantesPDCMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelHistorialVisitantesPDCMouseExited
        PanelHistorialVisitantesPDC.setBackground(new Color(29, 35, 51));
    }//GEN-LAST:event_PanelHistorialVisitantesPDCMouseExited

    private void BarraDeBusquedaCodigoVisitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarraDeBusquedaCodigoVisitasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BarraDeBusquedaCodigoVisitasActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BarraDeBusquedaCodigoVisitas;
    private javax.swing.JTextField BarraDeBusquedaPorIdentificacionVisitantes;
    private javax.swing.JButton BuscarVisitaPorCodigoBoton;
    private javax.swing.JButton BuscarVisitantePorIdentificacionPDC;
    private javax.swing.JPanel PanelHistorialVisitantes;
    private javax.swing.JPanel PanelHistorialVisitantesPDC;
    private javax.swing.JPanel PanelHistorialVisitas;
    private javax.swing.JPanel PanelHistorialVisitasPDC;
    private javax.swing.JTabbedPane TabbedHistorialVisitas;
    private javax.swing.JTable TablaHistorialVisitantesPDC;
    private javax.swing.JTable TablaHistorialVisitasPDC;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
