/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.Color;

/**
 *
 * @author ASUS
 */
public class OficialDeRegistro extends javax.swing.JFrame {

    /**
     * Creates new form OficialDeRegistro
     */
    public OficialDeRegistro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        PanelPresos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        PanelPerfil = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PanelAñadirPreso = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        OficialDeRegistroView = new javax.swing.JTabbedPane();
        PanelPerfilBase = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        PanelTablaPresoBase = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaPresos = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        PanelAñadirPresoBase = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelPresos.setBackground(new java.awt.Color(29, 35, 51));
        PanelPresos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelPresosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelPresosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelPresosMouseExited(evt);
            }
        });
        PanelPresos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PRESOS");
        PanelPresos.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 90, -1));

        jPanel5.add(PanelPresos, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 370, 60));

        PanelPerfil.setBackground(new java.awt.Color(29, 35, 51));
        PanelPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelPerfilMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelPerfilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelPerfilMouseExited(evt);
            }
        });
        PanelPerfil.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PERFIL");
        PanelPerfil.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jPanel5.add(PanelPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 60));

        PanelAñadirPreso.setBackground(new java.awt.Color(29, 35, 51));
        PanelAñadirPreso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelAñadirPresoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelAñadirPresoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelAñadirPresoMouseExited(evt);
            }
        });
        PanelAñadirPreso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("AÑADIR PRESO");
        PanelAñadirPreso.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 140, -1));

        jPanel5.add(PanelAñadirPreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 350, 60));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 60));

        PanelPerfilBase.setBackground(new java.awt.Color(255, 255, 255));
        PanelPerfilBase.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        PanelPerfilBase.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 280, 520));

        OficialDeRegistroView.addTab("Perfil", PanelPerfilBase);

        PanelTablaPresoBase.setBackground(new java.awt.Color(255, 255, 255));
        PanelTablaPresoBase.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaPresos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Foto", "Id", "Nombre", "Apellido", "Edad", "Identificación", "Nacionalidad"
            }
        ));
        jScrollPane1.setViewportView(TablaPresos);

        PanelTablaPresoBase.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 91, 900, 410));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        PanelTablaPresoBase.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 570, 40));

        jButton1.setText("Buscar");
        PanelTablaPresoBase.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 30, 90, 40));

        OficialDeRegistroView.addTab("Presos", PanelTablaPresoBase);

        PanelAñadirPresoBase.setBackground(new java.awt.Color(255, 255, 255));
        PanelAñadirPresoBase.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        OficialDeRegistroView.addTab("Añadir Preso", PanelAñadirPresoBase);

        jPanel1.add(OficialDeRegistroView, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1050, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PanelPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelPerfilMouseClicked

        OficialDeRegistroView.setSelectedIndex(0);

        
    }//GEN-LAST:event_PanelPerfilMouseClicked

    private void PanelPresosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelPresosMouseClicked

        OficialDeRegistroView.setSelectedIndex(1);

    }//GEN-LAST:event_PanelPresosMouseClicked

    private void PanelAñadirPresoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelAñadirPresoMouseClicked

        OficialDeRegistroView.setSelectedIndex(2);


    }//GEN-LAST:event_PanelAñadirPresoMouseClicked

    private void PanelPerfilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelPerfilMouseEntered

PanelPerfil.setBackground(new Color(43,54,84));
    }//GEN-LAST:event_PanelPerfilMouseEntered

    private void PanelPresosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelPresosMouseEntered
PanelPresos.setBackground(new Color(43,54,84));
    }//GEN-LAST:event_PanelPresosMouseEntered

    private void PanelAñadirPresoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelAñadirPresoMouseEntered
        PanelAñadirPreso.setBackground(new Color(43, 54, 84));
    }//GEN-LAST:event_PanelAñadirPresoMouseEntered

    private void PanelPerfilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelPerfilMouseExited

        PanelPerfil.setBackground(new Color(29,35,51));


    }//GEN-LAST:event_PanelPerfilMouseExited

    private void PanelPresosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelPresosMouseExited
        PanelPresos.setBackground(new Color(29,35,51));
    }//GEN-LAST:event_PanelPresosMouseExited

    private void PanelAñadirPresoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelAñadirPresoMouseExited
        PanelAñadirPreso.setBackground(new Color(29,35,51));
    }//GEN-LAST:event_PanelAñadirPresoMouseExited

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OficialDeRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OficialDeRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OficialDeRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OficialDeRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OficialDeRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane OficialDeRegistroView;
    private javax.swing.JPanel PanelAñadirPreso;
    private javax.swing.JPanel PanelAñadirPresoBase;
    private javax.swing.JPanel PanelPerfil;
    private javax.swing.JPanel PanelPerfilBase;
    private javax.swing.JPanel PanelPresos;
    private javax.swing.JPanel PanelTablaPresoBase;
    private javax.swing.JTable TablaPresos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
