/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author ASUS
 */
public class PersonalDeControl extends javax.swing.JFrame {

    /**
     * Creates new form PersonalDeControl
     */
    public PersonalDeControl() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PersonalDeControlView = new javax.swing.JTabbedPane();
        PanelPerfilPDC = new javax.swing.JPanel();
        PanelListaPresosPDC = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaPresosPDC = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        PanelAñadirVisitaPDC = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelPerfilPDC.setBackground(new java.awt.Color(255, 255, 255));
        PanelPerfilPDC.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        PersonalDeControlView.addTab("Perfil", PanelPerfilPDC);

        PanelListaPresosPDC.setBackground(new java.awt.Color(255, 255, 255));
        PanelListaPresosPDC.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaPresosPDC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Foto", "Id", "Nombre", "Apellido", "Edad", "Identificación", "Nacionalidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TablaPresosPDC);
        if (TablaPresosPDC.getColumnModel().getColumnCount() > 0) {
            TablaPresosPDC.getColumnModel().getColumn(0).setResizable(false);
            TablaPresosPDC.getColumnModel().getColumn(1).setResizable(false);
            TablaPresosPDC.getColumnModel().getColumn(2).setResizable(false);
            TablaPresosPDC.getColumnModel().getColumn(3).setResizable(false);
            TablaPresosPDC.getColumnModel().getColumn(4).setResizable(false);
            TablaPresosPDC.getColumnModel().getColumn(5).setResizable(false);
            TablaPresosPDC.getColumnModel().getColumn(6).setResizable(false);
        }

        PanelListaPresosPDC.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 77, 940, 420));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        PanelListaPresosPDC.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, -1, -1));

        PersonalDeControlView.addTab("Presos", PanelListaPresosPDC);

        PanelAñadirVisitaPDC.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PanelAñadirVisitaPDCLayout = new javax.swing.GroupLayout(PanelAñadirVisitaPDC);
        PanelAñadirVisitaPDC.setLayout(PanelAñadirVisitaPDCLayout);
        PanelAñadirVisitaPDCLayout.setHorizontalGroup(
            PanelAñadirVisitaPDCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1048, Short.MAX_VALUE)
        );
        PanelAñadirVisitaPDCLayout.setVerticalGroup(
            PanelAñadirVisitaPDCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 552, Short.MAX_VALUE)
        );

        PersonalDeControlView.addTab("Añadir visita", PanelAñadirVisitaPDC);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PersonalDeControlView)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PersonalDeControlView)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonalDeControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonalDeControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonalDeControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonalDeControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PersonalDeControl().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelAñadirVisitaPDC;
    private javax.swing.JPanel PanelListaPresosPDC;
    private javax.swing.JPanel PanelPerfilPDC;
    private javax.swing.JTabbedPane PersonalDeControlView;
    private javax.swing.JTable TablaPresosPDC;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
