/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DAO.GuardiaDAO;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import Model.Guardia;
import java.awt.Component;
import java.awt.Image;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gameV
 */
public class preView extends javax.swing.JFrame {

    private String rutaImagenFinal = ""; // Variable para almacenar la ruta de la imagen seleccionada

    /**
     * Creates new form preView
     */
    public preView() {
        initComponents();
        tablaGuardias.setModel(cargarGuardiasConImagen());
        ajustarImagenesTabla();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        Modificar = new javax.swing.JMenuItem();
        Eliminar = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        AgregarGuardia = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txtName = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtNacionalidad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cmbTurno = new javax.swing.JComboBox<>();
        cmbCargo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtFechaNacimiento = new javax.swing.JLabel();
        fechaNacimientoChooser = new com.toedter.calendar.JDateChooser();
        txtImagen = new javax.swing.JLabel();
        fondoFoto = new javax.swing.JPanel();
        previewFoto = new javax.swing.JLabel();
        chooseImg = new javax.swing.JButton();
        txtEdad = new javax.swing.JTextField();
        MostrarGuardia = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaGuardias = new javax.swing.JTable();
        ViewDirector = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        txtCorreoMod = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtNacionalidadMod = new javax.swing.JTextField();
        txtEdadMod = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cmbTurnoMod = new javax.swing.JComboBox<>();
        cmbCargoMod = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtApellidoMod = new javax.swing.JTextField();
        txtNombreMod = new javax.swing.JTextField();
        txtName1 = new javax.swing.JLabel();
        fondoFoto1 = new javax.swing.JPanel();
        previewFoto1 = new javax.swing.JLabel();
        chooseImg1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtCorreoMod1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtNacionalidadMod1 = new javax.swing.JTextField();
        txtEdadMod1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCedulaMod = new javax.swing.JTextField();

        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(Modificar);

        Eliminar.setText("Eliminar");
        jPopupMenu1.add(Eliminar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AgregarGuardia.setBackground(new java.awt.Color(255, 255, 255));
        AgregarGuardia.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Cedula");
        AgregarGuardia.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 70, -1));

        txtName.setForeground(new java.awt.Color(0, 0, 0));
        txtName.setText("Nombre:");
        AgregarGuardia.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 70, -1));

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Apellido:");
        AgregarGuardia.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 70, -1));
        AgregarGuardia.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 240, 30));

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Correo:");
        AgregarGuardia.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 70, 20));

        jButton1.setText("Contratar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        AgregarGuardia.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 110, -1));

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Edad");
        AgregarGuardia.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 70, -1));
        AgregarGuardia.add(txtNacionalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 240, -1));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Nacionalidad");
        AgregarGuardia.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 90, 20));

        cmbTurno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Diurno", "Nocturno" }));
        AgregarGuardia.add(cmbTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 240, -1));

        cmbCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Supervisor general", "Subinspector", "Custodio" }));
        AgregarGuardia.add(cmbCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 240, -1));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Cargo:");
        AgregarGuardia.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 70, 30));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Turno:");
        AgregarGuardia.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 70, 20));

        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });
        txtCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCedulaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCedulaKeyTyped(evt);
            }
        });
        AgregarGuardia.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 240, -1));
        AgregarGuardia.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 240, -1));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Apellido:");
        AgregarGuardia.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 70, -1));
        AgregarGuardia.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 240, -1));

        txtFechaNacimiento.setForeground(new java.awt.Color(0, 0, 0));
        txtFechaNacimiento.setText("Fecha de nacimiento:");
        AgregarGuardia.add(txtFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, -1, -1));
        AgregarGuardia.add(fechaNacimientoChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 50, 240, -1));

        txtImagen.setForeground(new java.awt.Color(0, 0, 0));
        txtImagen.setText("Imagen del guardia:");
        AgregarGuardia.add(txtImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 90, -1, -1));

        javax.swing.GroupLayout fondoFotoLayout = new javax.swing.GroupLayout(fondoFoto);
        fondoFoto.setLayout(fondoFotoLayout);
        fondoFotoLayout.setHorizontalGroup(
            fondoFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoFotoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(previewFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        fondoFotoLayout.setVerticalGroup(
            fondoFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoFotoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(previewFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        AgregarGuardia.add(fondoFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 120, 170, 200));

        chooseImg.setText("Seleccionar imagen");
        chooseImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseImgActionPerformed(evt);
            }
        });
        AgregarGuardia.add(chooseImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 340, -1, -1));

        txtEdad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEdadKeyTyped(evt);
            }
        });
        AgregarGuardia.add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 240, -1));

        jTabbedPane1.addTab("AgregarGuardia", AgregarGuardia);

        MostrarGuardia.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaGuardias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Foto", "Nombre", "Apellido", "Edad", "Identificación", "Cargo", "Turno", "Correo"
            }
        ));
        tablaGuardias.setComponentPopupMenu(jPopupMenu1);
        jScrollPane1.setViewportView(tablaGuardias);

        jScrollPane2.setViewportView(jScrollPane1);

        MostrarGuardia.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 970, 370));

        jTabbedPane1.addTab("MostrarGuardia", MostrarGuardia);

        javax.swing.GroupLayout ViewDirectorLayout = new javax.swing.GroupLayout(ViewDirector);
        ViewDirector.setLayout(ViewDirectorLayout);
        ViewDirectorLayout.setHorizontalGroup(
            ViewDirectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1040, Short.MAX_VALUE)
        );
        ViewDirectorLayout.setVerticalGroup(
            ViewDirectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 425, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("ViewDirector", ViewDirector);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("Modificar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 110, -1));
        jPanel2.add(txtCorreoMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 240, 30));

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Correo:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 70, 20));

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Nacionalidad");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 90, 20));
        jPanel2.add(txtNacionalidadMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 240, -1));

        txtEdadMod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEdadModKeyTyped(evt);
            }
        });
        jPanel2.add(txtEdadMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 240, -1));

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Edad");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 70, -1));

        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Turno:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 70, 20));

        cmbTurnoMod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Diurno", "Nocturno" }));
        jPanel2.add(cmbTurnoMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 240, -1));

        cmbCargoMod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Supervisor general", "Subinspector", "Custodio" }));
        jPanel2.add(cmbCargoMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 240, -1));

        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Cargo:");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 70, 30));

        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Apellido:");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 70, -1));
        jPanel2.add(txtApellidoMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 240, -1));
        jPanel2.add(txtNombreMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 240, -1));

        txtName1.setForeground(new java.awt.Color(0, 0, 0));
        txtName1.setText("Nombre:");
        jPanel2.add(txtName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 70, -1));

        javax.swing.GroupLayout fondoFoto1Layout = new javax.swing.GroupLayout(fondoFoto1);
        fondoFoto1.setLayout(fondoFoto1Layout);
        fondoFoto1Layout.setHorizontalGroup(
            fondoFoto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoFoto1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(previewFoto1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        fondoFoto1Layout.setVerticalGroup(
            fondoFoto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoFoto1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(previewFoto1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel2.add(fondoFoto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 80, 170, 200));

        chooseImg1.setText("Seleccionar");
        chooseImg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseImg1ActionPerformed(evt);
            }
        });
        jPanel2.add(chooseImg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 310, -1, -1));

        jButton3.setText("Contratar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 110, -1));
        jPanel2.add(txtCorreoMod1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 240, 30));

        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Nacionalidad");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 90, 20));

        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Correo:");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 70, 20));
        jPanel2.add(txtNacionalidadMod1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 240, -1));

        txtEdadMod1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEdadMod1KeyTyped(evt);
            }
        });
        jPanel2.add(txtEdadMod1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 240, -1));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Seleccionar nueva imagen: ");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 50, -1, -1));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Cedula:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 60, -1));
        jPanel2.add(txtCedulaMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 240, -1));

        jTabbedPane1.addTab("ModficarGuardia", jPanel2);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 1040, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1060, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public DefaultTableModel cargarGuardiasConImagen() {
        String[] columnas = {"Foto", "Nombres", "Apellido", "Edad", "Identificación", "Cargo", "Turno", "Correo"};
        DefaultTableModel modelo = new DefaultTableModel(null, columnas) {
            @Override
            public Class<?> getColumnClass(int columnIndex) {
                if (columnIndex == 0) {
                    return Icon.class; // Foto
                }
                return String.class;
            }

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        GuardiaDAO dao = new GuardiaDAO();
        List<Guardia> lista = dao.obtenerGuardias();

        for (Guardia g : lista) {
            ImageIcon icono = null;
            if (g.getRutaImagen() != null) {
                File imgFile = new File(g.getRutaImagen());
                if (imgFile.exists()) {
                    ImageIcon original = new ImageIcon(g.getRutaImagen());
                    Image imagenEscalada = original.getImage().getScaledInstance(60, 60, Image.SCALE_SMOOTH);
                    icono = new ImageIcon(imagenEscalada);
                }
            }

            modelo.addRow(new Object[]{
                icono,
                g.getNombre(),
                g.getApellido(),
                g.getEdad(),
                g.getCedula(),
                g.getCargo(),
                g.getTurno(),
                g.getCorreo()

            });
        }

        return modelo;
    }

    private void ajustarImagenesTabla() {
        tablaGuardias.getColumnModel().getColumn(0).setCellRenderer(new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,
                    boolean isSelected, boolean hasFocus, int row, int column) {
                if (value instanceof ImageIcon) {
                    JLabel lbl = new JLabel();
                    lbl.setIcon((ImageIcon) value);
                    lbl.setHorizontalAlignment(SwingConstants.CENTER);
                    return lbl;
                }
                return super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
            }
        });

        tablaGuardias.setRowHeight(80); // Altura de cada fila para que quepa la imagen
    }


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        

        
// Aquí pones el resto de tu código si el correo es válido
        if (rutaImagenFinal.isEmpty()) {
            JOptionPane.showMessageDialog(null, "¡Debes seleccionar una imagen para el guardia!");
            return; // Detener el flujo si no hay imagen seleccionada
        }

        // Obtener los datos del formulario
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String nombre = txtNombre.getText();
        String apellido = txtApellido.getText();
        String cedula = txtCedula.getText();
        String cargo = cmbCargo.getSelectedItem().toString();
        String turno = cmbTurno.getSelectedItem().toString();
        int edad = Integer.parseInt(txtEdad.getText());
        String nacionalidad = txtNacionalidad.getText();
        String correo = txtCorreo.getText();
        String fechaNacimiento = sdf.format(fechaNacimientoChooser.getDate());
        
        if (!correo.contains("@") || !correo.endsWith(".com")) {
            JOptionPane.showMessageDialog(null, "Por favor, ingresa un correo válido que contenga '@' y termine en '.com'.", "Correo inválido", JOptionPane.WARNING_MESSAGE);
            return; // no deja avanzar
        }


        // Crear objeto Guardia
        Guardia guardia = new Guardia(nombre, apellido, cedula, cargo, turno, edad, nacionalidad, correo, fechaNacimiento, rutaImagenFinal);

        // Guardar el guardia en el archivo JSON (puedes cambiarlo por base de datos si es necesario)
        GuardiaDAO dao = new GuardiaDAO();
        boolean exito = dao.guardarGuardia(guardia, new File(rutaImagenFinal));

        // Mostrar mensaje según si se guardó correctamente o no
        if (exito) {
            JOptionPane.showMessageDialog(null, "Guardia guardado correctamente 🎉");
        } else {
            JOptionPane.showMessageDialog(null, "Error al guardar el guardia 😓");
        }

        System.out.println("Ruta imagen: " + rutaImagenFinal);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void chooseImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseImgActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Selecciona la imagen del guardia");

// Solo permitir imágenes
        chooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Imágenes", "jpg", "jpeg", "png", "gif"));

        int opcion = chooser.showOpenDialog(null);

// Verificar si el usuario seleccionó una imagen
        if (opcion == JFileChooser.APPROVE_OPTION) {
            File imagenSeleccionada = chooser.getSelectedFile();

            // Verificar que la imagen seleccionada existe
            if (imagenSeleccionada != null && imagenSeleccionada.exists()) {
                // Mostrar vista previa en el JLabel previewFoto
                ImageIcon iconoOriginal = new ImageIcon(imagenSeleccionada.getAbsolutePath());
                Image imagenEscalada = iconoOriginal.getImage().getScaledInstance(142, 180, Image.SCALE_SMOOTH);
                previewFoto.setIcon(new ImageIcon(imagenEscalada));

                // Crear carpeta si no existe
                File carpeta = new File("imagenes_guardias");
                if (!carpeta.exists()) {
                    carpeta.mkdirs();
                }

                // Preparar la ruta y nombre final
                String nombreImagen = txtCedula.getText() + "_" + imagenSeleccionada.getName().replace(" ", "_");
                rutaImagenFinal = "imagenes_guardias/" + nombreImagen;

                // Copiar la imagen seleccionada a la carpeta de guardias
                try {
                    Files.copy(imagenSeleccionada.toPath(), Paths.get(rutaImagenFinal), StandardCopyOption.REPLACE_EXISTING);
                    JOptionPane.showMessageDialog(null, "¡Imagen seleccionada correctamente!");
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(null, "Error al guardar la imagen: " + ex.getMessage());
                }
            }
        }


    }//GEN-LAST:event_chooseImgActionPerformed

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaActionPerformed

    private void txtCedulaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaKeyPressed

    private void txtCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && c != '\b') {
    evt.consume(); // no deja que se escriba

    // solo muestra el mensaje si no es backspace
    if (c != '\b') {
        JOptionPane.showMessageDialog(null, "Solo se permiten números.", "Entrada inválida", JOptionPane.WARNING_MESSAGE);
    }
        }
    }//GEN-LAST:event_txtCedulaKeyTyped

    private void txtEdadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEdadKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && c != '\b') {
    evt.consume(); // no deja que se escriba

    // solo muestra el mensaje si no es backspace
    if (c != '\b') {
        JOptionPane.showMessageDialog(null, "Solo se permiten números.", "Entrada inválida", JOptionPane.WARNING_MESSAGE);
    }
        }
    }//GEN-LAST:event_txtEdadKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 

    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtEdadModKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEdadModKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdadModKeyTyped

    private void chooseImg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseImg1ActionPerformed
                                     
   

    }//GEN-LAST:event_chooseImg1ActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
       
   
    


    }//GEN-LAST:event_ModificarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtEdadMod1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEdadMod1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdadMod1KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(preView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(preView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(preView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(preView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new preView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AgregarGuardia;
    private javax.swing.JMenuItem Eliminar;
    private javax.swing.JMenuItem Modificar;
    private javax.swing.JPanel MostrarGuardia;
    private javax.swing.JPanel ViewDirector;
    private javax.swing.JButton chooseImg;
    private javax.swing.JButton chooseImg1;
    private javax.swing.JComboBox<String> cmbCargo;
    private javax.swing.JComboBox<String> cmbCargoMod;
    private javax.swing.JComboBox<String> cmbTurno;
    private javax.swing.JComboBox<String> cmbTurnoMod;
    private com.toedter.calendar.JDateChooser fechaNacimientoChooser;
    private javax.swing.JPanel fondoFoto;
    private javax.swing.JPanel fondoFoto1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel previewFoto;
    private javax.swing.JLabel previewFoto1;
    private javax.swing.JTable tablaGuardias;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtApellidoMod;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCedulaMod;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtCorreoMod;
    private javax.swing.JTextField txtCorreoMod1;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtEdadMod;
    private javax.swing.JTextField txtEdadMod1;
    private javax.swing.JLabel txtFechaNacimiento;
    private javax.swing.JLabel txtImagen;
    private javax.swing.JTextField txtNacionalidad;
    private javax.swing.JTextField txtNacionalidadMod;
    private javax.swing.JTextField txtNacionalidadMod1;
    private javax.swing.JLabel txtName;
    private javax.swing.JLabel txtName1;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreMod;
    // End of variables declaration//GEN-END:variables
}
